sayilar=[1,10,5,16,4,9,10]
harfler=['a','g','s','c','z','a','s']
sonuc=min(sayilar)
sonuc=max(sayilar)
sonuc=min(harfler)
sonuc=max(harfler)
sonuc=sayilar[3:6]
sonuc=sayilar[:3]
sonuc=sayilar[4:]
sayilar[4]=40
sayilar.append(49)
sayilar.append(59)
sayilar.insert(3,78)
sayilar.insert(-1,52)
sayilar.pop()
sayilar.pop(0)
sayilar.pop(-1)
sayilar.remove(49)
sayilar.sort()
sayilar.reverse()
harfler.sort()
harfler.reverse()
print(harfler.count('a'))
print(sayilar.count(5))
# sayilar.clear()
print(sayilar)
print(harfler)
print(len(sayilar))
print(len(harfler))
